
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CANOPENSHELLMASTEROD_H
#define CANOPENSHELLMASTEROD_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 CANOpenShellMasterOD_valueRangeTest (UNS8 typeValue, void * value);
const indextable * CANOpenShellMasterOD_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data CANOpenShellMasterOD_Data;
extern INTEGER32 R1_position;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER32 R2_position;		/* Mapped at index 0x2001, subindex 0x00*/
extern INTEGER32 R3_position;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER32 R4_position;		/* Mapped at index 0x2003, subindex 0x00*/
extern INTEGER32 R5_position;		/* Mapped at index 0x2004, subindex 0x00*/
extern INTEGER32 R6_position;		/* Mapped at index 0x2005, subindex 0x00*/
extern INTEGER32 R7_position;		/* Mapped at index 0x2006, subindex 0x00*/
extern INTEGER32 R8_position;		/* Mapped at index 0x2007, subindex 0x00*/
extern INTEGER32 R9_position;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 R1_statusword;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS16 R2_statusword;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS16 R3_statusword;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS16 R4_statusword;		/* Mapped at index 0x2013, subindex 0x00*/
extern UNS16 R5_statusword;		/* Mapped at index 0x2014, subindex 0x00*/
extern UNS16 R6_statusword;		/* Mapped at index 0x2015, subindex 0x00*/
extern UNS16 R7_statusword;		/* Mapped at index 0x2016, subindex 0x00*/
extern UNS16 R8_statusword;		/* Mapped at index 0x2017, subindex 0x00*/
extern UNS16 R9_statusword;		/* Mapped at index 0x2018, subindex 0x00*/
extern INTEGER8 R1_Display_Mode_of_operation;		/* Mapped at index 0x2020, subindex 0x00*/
extern INTEGER8 R2_Display_Mode_of_operation;		/* Mapped at index 0x2021, subindex 0x00*/
extern INTEGER8 R3_Display_Mode_of_operation;		/* Mapped at index 0x2022, subindex 0x00*/
extern INTEGER8 R4_Display_Mode_of_operation;		/* Mapped at index 0x2023, subindex 0x00*/
extern INTEGER8 R5_Display_Mode_of_operation;		/* Mapped at index 0x2024, subindex 0x00*/
extern INTEGER8 R6_Display_Mode_of_operation;		/* Mapped at index 0x2025, subindex 0x00*/
extern INTEGER8 R7_Display_Mode_of_operation;		/* Mapped at index 0x2026, subindex 0x00*/
extern INTEGER8 R8_Display_Mode_of_operation;		/* Mapped at index 0x2027, subindex 0x00*/
extern INTEGER8 R9_Display_Mode_of_operation;		/* Mapped at index 0x2028, subindex 0x00*/
extern INTEGER32 R1_speed;		/* Mapped at index 0x2100, subindex 0x00*/
extern INTEGER32 R2_speed;		/* Mapped at index 0x2101, subindex 0x00*/
extern INTEGER32 R3_speed;		/* Mapped at index 0x2102, subindex 0x00*/
extern INTEGER32 R4_speed;		/* Mapped at index 0x2103, subindex 0x00*/
extern INTEGER32 R5_speed;		/* Mapped at index 0x2104, subindex 0x00*/
extern INTEGER32 R6_speed;		/* Mapped at index 0x2105, subindex 0x00*/
extern INTEGER32 R7_speed;		/* Mapped at index 0x2106, subindex 0x00*/
extern INTEGER32 R8_speed;		/* Mapped at index 0x2107, subindex 0x00*/
extern INTEGER32 R9_speed;		/* Mapped at index 0x2108, subindex 0x00*/
extern UNS16 M1_TPDO_control_word;		/* Mapped at index 0x2201, subindex 0x00*/
extern UNS16 M2_TPDO_control_word;		/* Mapped at index 0x2202, subindex 0x00*/
extern UNS16 M3_TPDO_control_word;		/* Mapped at index 0x2203, subindex 0x00*/
extern INTEGER8 M1_TPDO_mode_of_operation;		/* Mapped at index 0x2301, subindex 0x00*/
extern INTEGER8 M2_TPDO_mode_of_operation;		/* Mapped at index 0x2302, subindex 0x00*/
extern INTEGER8 M3_TPDO_mode_of_operation;		/* Mapped at index 0x2303, subindex 0x00*/
extern INTEGER32 M1_TPDO_target_speed;		/* Mapped at index 0x2401, subindex 0x00*/
extern INTEGER32 M2_TPDO_target_speed;		/* Mapped at index 0x2402, subindex 0x00*/
extern INTEGER32 M3_TPDO_target_speed;		/* Mapped at index 0x2403, subindex 0x00*/
extern INTEGER32 M2_5_TPDO_target_speed;		/* Mapped at index 0x2405, subindex 0x00*/
extern INTEGER32 M2_6_TPDO_target_speed;		/* Mapped at index 0x2406, subindex 0x00*/
extern INTEGER32 M2_7_TPDO_target_speed;		/* Mapped at index 0x2407, subindex 0x00*/
extern INTEGER32 M2_8_TPDO_target_speed;		/* Mapped at index 0x2408, subindex 0x00*/
extern INTEGER32 M1_1_TPDO_target_speed;		/* Mapped at index 0x2411, subindex 0x00*/
extern INTEGER32 M1_2_TPDO_target_speed;		/* Mapped at index 0x2412, subindex 0x00*/
extern INTEGER32 M1_3_TPDO_target_speed;		/* Mapped at index 0x2413, subindex 0x00*/
extern INTEGER32 M1_4_TPDO_target_speed;		/* Mapped at index 0x2414, subindex 0x00*/
extern INTEGER32 M1_TPDO_Target_Position;		/* Mapped at index 0x2441, subindex 0x00*/
extern INTEGER32 M2_TPDO_Target_Position;		/* Mapped at index 0x2442, subindex 0x00*/
extern INTEGER32 M3_TPDO_Target_Position;		/* Mapped at index 0x2443, subindex 0x00*/
extern INTEGER32 M2_5_TPDO_Target_Position;		/* Mapped at index 0x2445, subindex 0x00*/
extern INTEGER32 M2_6_TPDO_Target_Position;		/* Mapped at index 0x2446, subindex 0x00*/
extern INTEGER32 M2_7_TPDO_Target_Position;		/* Mapped at index 0x2447, subindex 0x00*/
extern INTEGER32 M2_8_TPDO_Target_Position;		/* Mapped at index 0x2448, subindex 0x00*/
extern INTEGER16 M1_TPDO_Target_Torque;		/* Mapped at index 0x2451, subindex 0x00*/
extern INTEGER16 M2_TPDO_Target_Torque;		/* Mapped at index 0x2452, subindex 0x00*/
extern INTEGER16 M3_TPDO_Target_Torque;		/* Mapped at index 0x2453, subindex 0x00*/
extern INTEGER16 M2_5_TPDO_Target_Torque;		/* Mapped at index 0x2455, subindex 0x00*/
extern INTEGER16 M2_6_TPDO_Target_Torque;		/* Mapped at index 0x2456, subindex 0x00*/
extern INTEGER16 M2_7_TPDO_Target_Torque;		/* Mapped at index 0x2457, subindex 0x00*/
extern INTEGER16 M2_8_TPDO_Target_Torque;		/* Mapped at index 0x2458, subindex 0x00*/
extern INTEGER32 M1_1_TPDO_Target_Position;		/* Mapped at index 0x2461, subindex 0x00*/
extern INTEGER32 M1_2_TPDO_Target_Position;		/* Mapped at index 0x2462, subindex 0x00*/
extern INTEGER32 M1_3_TPDO_Target_Position;		/* Mapped at index 0x2463, subindex 0x00*/
extern INTEGER32 M1_4_TPDO_Target_Position;		/* Mapped at index 0x2464, subindex 0x00*/
extern INTEGER16 M1_1_TPDO_Target_Torque;		/* Mapped at index 0x2471, subindex 0x00*/
extern INTEGER16 M1_2_TPDO_Target_Torque;		/* Mapped at index 0x2472, subindex 0x00*/
extern INTEGER16 M1_3_TPDO_Target_Torque;		/* Mapped at index 0x2473, subindex 0x00*/
extern INTEGER16 M1_4_TPDO_Target_Torque;		/* Mapped at index 0x2474, subindex 0x00*/
extern INTEGER16 M1_TPDO_Motion_profile_type;		/* Mapped at index 0x2501, subindex 0x00*/
extern INTEGER16 M2_TPDO_Motion_profile_type;		/* Mapped at index 0x2502, subindex 0x00*/
extern INTEGER16 M3_TPDO_Motion_profile_type;		/* Mapped at index 0x2503, subindex 0x00*/
extern INTEGER32 M1_TPDO_Profile_Velocity;		/* Mapped at index 0x2601, subindex 0x00*/
extern INTEGER32 M2_TPDO_Profile_Velocity;		/* Mapped at index 0x2602, subindex 0x00*/
extern INTEGER32 M3_TPDO_Profile_Velocity;		/* Mapped at index 0x2603, subindex 0x00*/
extern INTEGER32 M2_5_TPDO_Profile_Velocity;		/* Mapped at index 0x2605, subindex 0x00*/
extern INTEGER32 M2_6_TPDO_Profile_Velocity;		/* Mapped at index 0x2606, subindex 0x00*/
extern INTEGER32 M2_7_TPDO_Profile_Velocity;		/* Mapped at index 0x2607, subindex 0x00*/
extern INTEGER32 M2_8_TPDO_Profile_Velocity;		/* Mapped at index 0x2608, subindex 0x00*/
extern INTEGER32 M1_1_TPDO_Profile_Velocity;		/* Mapped at index 0x2609, subindex 0x00*/
extern INTEGER32 M1_2_TPDO_Profile_Velocity;		/* Mapped at index 0x260A, subindex 0x00*/
extern INTEGER32 M1_3_TPDO_Profile_Velocity;		/* Mapped at index 0x260B, subindex 0x00*/
extern INTEGER32 M1_4_TPDO_Profile_Velocity;		/* Mapped at index 0x260C, subindex 0x00*/
extern INTEGER32 M1_TPDO_Profile_Acceleration;		/* Mapped at index 0x2701, subindex 0x00*/
extern INTEGER32 M2_TPDO_Profile_Acceleration;		/* Mapped at index 0x2702, subindex 0x00*/
extern INTEGER32 M3_TPDO_Profile_Acceleration;		/* Mapped at index 0x2703, subindex 0x00*/
extern INTEGER32 M2_5_TPDO_Profile_Acceleration;		/* Mapped at index 0x2705, subindex 0x00*/
extern INTEGER32 M2_6_TPDO_Profile_Acceleration;		/* Mapped at index 0x2706, subindex 0x00*/
extern INTEGER32 M2_7_TPDO_Profile_Acceleration;		/* Mapped at index 0x2707, subindex 0x00*/
extern INTEGER32 M2_8_TPDO_Profile_Acceleration;		/* Mapped at index 0x2708, subindex 0x00*/
extern INTEGER32 M1_1_TPDO_Profile_Acceleration;		/* Mapped at index 0x2711, subindex 0x00*/
extern INTEGER32 M1_2_TPDO_Profile_Acceleration;		/* Mapped at index 0x2712, subindex 0x00*/
extern INTEGER32 M1_3_TPDO_Profile_Acceleration;		/* Mapped at index 0x2713, subindex 0x00*/
extern INTEGER32 M1_4_TPDO_Profile_Acceleration;		/* Mapped at index 0x2714, subindex 0x00*/
extern INTEGER32 M1_TPDO_Profile_Deceleration;		/* Mapped at index 0x2801, subindex 0x00*/
extern INTEGER32 M2_TPDO_Profile_Deceleration;		/* Mapped at index 0x2802, subindex 0x00*/
extern INTEGER32 M3_TPDO_Profile_Deceleration;		/* Mapped at index 0x2803, subindex 0x00*/
extern INTEGER32 M2_5_TPDO_Profile_Deceleration;		/* Mapped at index 0x2805, subindex 0x00*/
extern INTEGER32 M2_6_TPDO_Profile_Deceleration;		/* Mapped at index 0x2806, subindex 0x00*/
extern INTEGER32 M2_7_TPDO_Profile_Deceleration;		/* Mapped at index 0x2807, subindex 0x00*/
extern INTEGER32 M2_8_TPDO_Profile_Deceleration;		/* Mapped at index 0x2808, subindex 0x00*/
extern INTEGER32 M1_1_TPDO_Profile_Deceleration;		/* Mapped at index 0x2811, subindex 0x00*/
extern INTEGER32 M1_2_TPDO_Profile_Deceleration;		/* Mapped at index 0x2812, subindex 0x00*/
extern INTEGER32 M1_3_TPDO_Profile_Deceleration;		/* Mapped at index 0x2813, subindex 0x00*/
extern INTEGER32 M1_4_TPDO_Profile_Deceleration;		/* Mapped at index 0x2814, subindex 0x00*/
extern UNS8 IN1_NAVI1_bit1_8;		/* Mapped at index 0x3001, subindex 0x00*/
extern UNS8 IN1_NAVI1_bit9_16;		/* Mapped at index 0x3002, subindex 0x00*/
extern UNS8 IN2_NAVI2_bit1_8;		/* Mapped at index 0x3003, subindex 0x00*/
extern UNS8 IN2_NAVI2_bit9_16;		/* Mapped at index 0x3004, subindex 0x00*/
extern UNS8 IN3_NAVI3_bit1_8;		/* Mapped at index 0x3005, subindex 0x00*/
extern UNS8 IN3_NAVI3_bit9_16;		/* Mapped at index 0x3006, subindex 0x00*/
extern UNS8 IN4_NAVI4_bit1_8;		/* Mapped at index 0x3007, subindex 0x00*/
extern UNS8 IN4_NAVI4_bit9_16;		/* Mapped at index 0x3008, subindex 0x00*/
extern UNS8 IN5_Limit_Switch_bit1_8;		/* Mapped at index 0x3009, subindex 0x00*/
extern UNS8 IN5_Limit_Switch_bit9_10;		/* Mapped at index 0x300A, subindex 0x00*/
extern UNS8 IN6_DLS1_4_bit1_8;		/* Mapped at index 0x300B, subindex 0x00*/
extern UNS8 IN6_Remoter_bit9_16;		/* Mapped at index 0x300C, subindex 0x00*/
extern UNS8 OUT7_DLS_Control_Zone_bit1_8;		/* Mapped at index 0x3011, subindex 0x00*/
extern UNS8 OUT7_DLS_Control_Zone_bit9_16;		/* Mapped at index 0x3012, subindex 0x00*/
extern UNS8 OUT8_Relay_bit1_8;		/* Mapped at index 0x3013, subindex 0x00*/
extern UNS8 PGV_Status_ST08_ST15;		/* Mapped at index 0x3014, subindex 0x00*/
extern UNS8 PGV_Status_ST00_ST07;		/* Mapped at index 0x3015, subindex 0x00*/
extern UNS8 PGV_Warning_WRN08_15;		/* Mapped at index 0x3016, subindex 0x00*/
extern UNS8 PGV_Warning_WRN00_07;		/* Mapped at index 0x3017, subindex 0x00*/
extern UNS8 PGV_Data_Matrixtag_TAG24_TAG31;		/* Mapped at index 0x3018, subindex 0x00*/
extern UNS8 PGV_Data_Matrixtag_TAG16_TAG23;		/* Mapped at index 0x3019, subindex 0x00*/
extern UNS8 PGV_Data_Matrixtag_TAG08_TAG15;		/* Mapped at index 0x301A, subindex 0x00*/
extern UNS8 PGV_Data_Matrixtag_TAG00_TAG07;		/* Mapped at index 0x301B, subindex 0x00*/

#endif // CANOPENSHELLMASTEROD_H
